### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by abolfazlMKazemi** [glomatico/votify#21] opened 2024-11-17 08:09 UTC
i get error 403 please help me
votify "https://open.spotify.com/track/18gqCQzqYb0zvurQPlRkpo"

[INFO     11:38:22] Starting Votify
[INFO     11:38:23] (URL 1/1) Checking "https://open.spotify.com/track/18gqCQzqYb0zvurQPlRkpo"
[INFO     11:38:25] (Track 1/1 from URL 1/1) Downloading "Never Gonna Give You Up - 2022 Remaster"
[ERROR    11:38:30] (Track 1/1 from URL 1/1) Failed to download "Never Gonna Give You Up - 2022 Remaster"
Traceback (most recent call last):
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/utils.py", line 8, in check_response
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gew4-spclient.spotify.com/playplay/v1/key/b7098e5bb8c2c1639bb44e0c17549e6d9f24bb3f

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/cli.py", line 597, in main
    downloader_song.download(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        track_id=media_id,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        playlist_track=index,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/downloader_audio.py", line 98, in get_decryption_key
    decryption_key = self.downloader.get_playplay_decryption_key(
        stream_info.file_id
    )
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/downloader.py", line 381, in get_playplay_decryption_key
    playplay_license_response_bytes = self.spotify_api.get_playplay_license(
        file_id,
        playplay_license_request.SerializeToString(),
    )
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/spotify_api.py", line 287, in get_playplay_license
    check_response(response)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/utils.py", line 10, in check_response
    _raise_response_exception(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/abolfazl/Documents/melobot/crack/Votify spotify downloader/venv/lib/python3.13/site-packages/votify/utils.py", line 14, in _raise_response_exception
    raise Exception(
        f"Request failed with status code {response.status_code}: {response.text}"
    )
Exception: Request failed with status code 403: 
[INFO     11:38:30] Done (1 error(s))

**Comment by glomatico** [comment] 2024-11-19 19:47
duplicate of #5

**Closed by glomatico** 2024-11-19 19:47 UTC
