### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Abhi5033** [glomatico/votify#19] opened 2024-11-11 06:26 UTC
![image](https://github.com/user-attachments/assets/4d9238fe-a055-4bfb-a81c-2940c491e069)
Updated re-unplayplay but still

**Comment by jaguarondi** [comment] 2024-11-11 10:50
I have exactly the same error:
re-unplayplay==1.2.6
votify==1.4.4

**Comment by s0llvan** [comment] 2024-11-11 20:58
Same error
Votify : 1.4.4

**Comment by dgottstein** [comment] 2024-11-12 21:32
Same error here, Votify 1.4.4...

**Comment by glomatico** [comment] 2024-11-14 09:39
Duplicate of #5

**Closed by glomatico** 2024-11-14 09:39 UTC
